# Generated by Django 4.2.4 on 2023-11-27 23:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('localizacao', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('TEMPO_INTEGRAL', 'Tempo integral'), ('MEIO_PERIODO', 'Meio período'), ('CONTRATADO', 'Contratado'), ('TEMPORARIO', 'Temporário'), ('ESTAGIARIO', 'Estagiário'), ('VOLUNTARIO', 'Voluntário'), ('DIARISTA', 'Diarista'), ('OUTRO', 'Outro')], max_length=50)),
                ('url', models.URLField()),
                ('organizacao', models.CharField(max_length=255)),
                ('salario', models.CharField(blank=True, max_length=255, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('adicional_logo', models.BooleanField(default=False)),
                ('destacado', models.BooleanField(default=False)),
                ('cor_destaque_adicional', models.CharField(blank=True, max_length=7, null=True)),
                ('impulso_semanal_adicional', models.BooleanField(default=False)),
                ('impulso_diario_adicional', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(limit_choices_to={'tipo': 'EMPRESA'}, on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='VagaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.tag')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.vaga')),
            ],
            options={
                'unique_together': {('vaga', 'tag')},
            },
        ),
    ]
