# Generated by Django 4.2.4 on 2023-12-05 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('localizacao', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('TEMPO_INTEGRAL', 'Tempo integral'), ('MEIO_PERIODO', 'Meio período'), ('CONTRATADO', 'Contratado'), ('TEMPORARIO', 'Temporário'), ('ESTAGIARIO', 'Estagiário'), ('VOLUNTARIO', 'Voluntário'), ('DIARISTA', 'Diarista'), ('OUTRO', 'Outro')], max_length=50)),
                ('descricao', models.TextField()),
                ('organizacao', models.CharField(max_length=255)),
                ('salario', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
